# Generated by Django 2.2.12 on 2021-02-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='FIR_content',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
