# Generated by Django 2.2.12 on 2021-02-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210218_1803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='FIR',
        ),
    ]
